# Generated by cdo. Regenerate with: cdo sync
get_filename_component(CDO_PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

function(cdo_apply_dependencies target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "cdo_apply_dependencies called for unknown target: ${target}")
    endif()
endfunction()

function(cdo_copy_runtime_dependencies target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "cdo_copy_runtime_dependencies called for unknown target: ${target}")
    endif()
endfunction()

